/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AppBrowser: typeof import('./src/components/appBrowser/index.vue')['default']
    Application: typeof import('./src/components/application/index.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Calendar: typeof import('./src/components/application/calender/calendar.vue')['default']
    CalendarBox: typeof import('./src/components/application/calender/calendarBox.vue')['default']
    Controlbar: typeof import('./src/components/controlbar/index.vue')['default']
    ControlBar: typeof import('./src/components/controlBar/index.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/index.vue')['default']
    HomeMenu: typeof import('./src/components/menu/homeMenu.vue')['default']
    IIcBaselineSettings: typeof import('~icons/ic/baseline-settings')['default']
    ISystemUiconsAlignVertical: typeof import("~icons/system-uicons/align-vertical")["default"]
    ISystemUiconsArrowLeft: typeof import('~icons/system-uicons/arrow-left')['default']
    ISystemUiconsArrowRight: typeof import('~icons/system-uicons/arrow-right')['default']
    ISystemUiconsHomeAlt: typeof import('~icons/system-uicons/home-alt')['default']
    ISystemUiconsPanelSectioned: typeof import('~icons/system-uicons/panel-sectioned')['default']
    ISystemUiconsUserMaleCircle: typeof import('~icons/system-uicons/user-male-circle')['default']
    IWiDaySunny: typeof import('~icons/wi/day-sunny')['default']
    IWiMoonWaxingCrescent6: typeof import('~icons/wi/moon-waxing-crescent6')['default']
    Menu: typeof import('./src/components/menu/index.vue')['default']
    RightMenu: typeof import('./src/components/menu/rightMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/searchInput/index.vue')['default']
    Slidebar: typeof import('./src/components/slidebar/index.vue')['default']
    Todo: typeof import('./src/components/application/todo/todo.vue')['default']
    Weather: typeof import('./src/components/application/weather/weather.vue')['default']
    WeatherBox: typeof import('./src/components/application/weather/weatherBox.vue')['default']
  }
}
