export const config = {
  defaultApps: [
    {
      size: "large",
      title: "日历",
      type: "component",
      component: "calendar",
    },
    {
      size: "large",
      title: "天气",
      type: "component",
      component: "weather",
    },
    {
      size: "large",
      title: "待办事项",
      type: "component",
      component: "todo",
    },
    {
      size: "small",
      title: "哔哩哔哩",
      type: "website",
      url: "https://www.bilibili.com/",
      iconType: "img",
      icon: "bilibili",
    },
    {
      size: "small",
      title: "知乎",
      type: "website",
      url: "https://www.zhihu.com/",
      iconType: "img",
      icon: "zhihu",
    },
    {
      size: "small",
      title: "百度贴吧",
      type: "website",
      url: "https://tieba.baidu.com/",
      iconType: "img",
      icon: "tieba",
    },

    {
      size: "small",
      title: "QQ音乐",
      type: "website",
      url: "https://y.qq.com/",
      iconType: "img",
      icon: "qqmusic",
    },
    {
      size: "small",
      title: "网易云音乐",
      type: "website",
      url: "https://music.163.com/",
      iconType: "img",
      icon: "netease",
    },
    {
      size: "small",
      title: "微博",
      type: "website",
      url: "https://weibo.com/",
      iconType: "img",
      icon: "weibo",
    },
  ],
};
